"""added types

Revision ID: cb1e9421b41a
Revises: d87712e7a365
Create Date: 2025-11-13 19:44:27.605507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1e9421b41a'
down_revision: Union[str, None] = 'd87712e7a365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_job', sa.Column('operating_mode', sa.String(length=255), nullable=True))
    op.add_column('design_job', sa.Column('run_time_in_seconds', sa.Integer(), nullable=True))
    op.add_column('design_job', sa.Column('parent_design_job_id', sa.UUID(), nullable=True))
    op.add_column('design_job', sa.Column('is_child_design_job', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_job', 'is_child_design_job')
    op.drop_column('design_job', 'parent_design_job_id')
    op.drop_column('design_job', 'run_time_in_seconds')
    op.drop_column('design_job', 'operating_mode')
    # ### end Alembic commands ###