"""added pipeline name

Revision ID: d87712e7a365
Revises: c1a832156193
Create Date: 2025-11-12 03:28:51.800788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87712e7a365'
down_revision: Union[str, None] = 'c1a832156193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_job', sa.Column('pipeline_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_job', 'pipeline_name')
    # ### end Alembic commands ###